server:
  port: 8092
  host: localhost
spring:
  application:
    name: RegistrationAPI
  zipkin:
    baseUrl: http://localhost:9411/zipkin/
  data:
    mongodb:
      database: signup_db
      port: 27017
      host: localhost
  mail:
    host: smtp.gmail.com
    properties:
      mail:
        smtp:
          auth: false
        starttls: true
    port: 587
  devtools:
      enabled: true

management:
  endpoint:
    health:
      enabled: true
      show-details: always
    metrics:
      tags:
        application: RegistrationAPI
  endpoints:
    web:
      exposure:
        include: "*"
    cors:
      allowed-origin: true

  metrics:
    tags:
      application: "RegistrationAPI"
hystrix:
  dashboard:
    proxy-stream-allow-list: "127.0.0.1"


app:
  jwtSecret: "*S*E*C*R*E*T*K*E*Y"
  jwtExpiration: 8640000


recaptcha:
  verification:
    endpoint: https://www.google.com/recaptcha/api/siteverify
  secret: 6LfBMe0aAAAAAMm5nCS8kqrMsbhgJzBXU6U1OWDE






